In [56]:
import numpy as np

batch_size = 4
seq_len = 10
n_vocab = 200

# synthetic sequences of tokens
sequences = np.random.randint(0, n_vocab, size=(batch_size, seq_len))

# synthetic logits matrix, which I would obtain by running my network over the sequences
logits = np.random.normal(size=(batch_size, seq_len, n_vocab)) 

# select the appropriate logits from the matrix using the sequences tokens as indices
# question: is there a more numpyic way of doing thing? 
seq_scores = np.array([
    [logits[batch, step, token]for step, token in enumerate(sequence)] 
    for batch, sequence in enumerate(sequences)
])

seq_scores[0,0] == logits[0,0,sequences[0,0]] # True
seq_scores.shape == sequences.shape # True

True

### Optimization...

In [105]:
%timeit np.repeat(list(range(batch_size)), seq_len).reshape(-1, seq_len)

6.37 µs ± 241 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [109]:
%timeit  [[x] * seq_len for x in range(batch_size)]

987 ns ± 19.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [122]:
%timeit list(zip(*seq_len * [list(range(batch_size))]))

1.51 µs ± 51.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [123]:
list(zip(*seq_len * [list(range(batch_size))]))

[(0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
 (1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
 (2, 2, 2, 2, 2, 2, 2, 2, 2, 2),
 (3, 3, 3, 3, 3, 3, 3, 3, 3, 3)]

In [111]:
[[x] * seq_len for x in range(batch_size)]

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]

In [97]:
i1 = np.repeat(list(range(batch_size)), seq_len).reshape(-1, seq_len)
i1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [98]:
i2 = batch_size * [list(range(seq_len))]
i2

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [85]:
sequences

array([[187,  89, 153, 101,   3,  14, 157,  25,  71,  93],
       [129, 109, 128,  46,  16,  77,  75, 126, 127, 142],
       [ 68,  54, 146, 163, 103, 188,  38,   4,  60, 153],
       [ 29, 183, 178,  31, 186,  73,  61, 143, 196, 149]])

### Let's do it!

In [99]:
logits[i1,i2, sequences].shape

(4, 10)

In [101]:
seq_scores2 = logits[i1,i2, sequences]

In [102]:
seq_scores == seq_scores2

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

### Tests.

In [104]:
%timeit seq_scores = np.array([[logits[batch, step, token]for step, token in enumerate(sequence)] for batch, sequence in enumerate(sequences)])

23.3 µs ± 393 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [107]:
%timeit logits[np.repeat(list(range(batch_size)), seq_len).reshape(-1, seq_len), batch_size * [list(range(seq_len))], sequences]

15 µs ± 553 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [112]:
%timeit logits[[[x] * seq_len for x in range(batch_size)], batch_size * [list(range(seq_len))], sequences]

13.3 µs ± 257 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
